import type { Event } from '@/lib/types';

export const events: Event[] = [
  {
    id: '1',
    title: 'Next.js Global Summit',
    date: '2024-09-15',
    time: '09:00',
    location: 'Online',
    description: 'Join developers from around the world for the latest in Next.js, Vercel, and modern web development. Keynotes, workshops, and networking opportunities.',
    category: 'Seminar',
  },
  {
    id: '2',
    title: 'AI in Practice: Workshop',
    date: '2024-09-20',
    time: '14:00',
    location: 'Tech Hub, Room 202',
    description: 'A hands-on workshop on implementing machine learning models in real-world applications using Python and TensorFlow.',
    category: 'Workshop',
  },
  {
    id: '3',
    title: 'Campus Innovate Hackathon',
    date: '2024-10-05',
    time: '18:00',
    location: 'Engineering Building',
    description: 'A 24-hour hackathon focused on creating innovative solutions for campus life. Prizes, food, and fun included!',
    category: 'Hackathon',
  },
  {
    id: '4',
    title: 'Tech Founders Networking Night',
    date: '2024-09-28',
    time: '19:00',
    location: 'Alumni Center',
    description: 'Meet and connect with fellow student entrepreneurs, local startup founders, and investors. Light refreshments will be served.',
    category: 'Networking',
  },
  {
    id: '5',
    title: 'The Future of Web3',
    date: '2024-10-12',
    time: '16:30',
    location: 'Lecture Hall C',
    description: 'A deep dive into blockchain technology, NFTs, and the decentralized web with industry expert Dr. Evelyn Reed.',
    category: 'Tech Talk',
  },
  {
    id: '6',
    title: 'Advanced CSS Techniques',
    date: '2024-09-25',
    time: '11:00',
    location: 'Design Lab, Art Building',
    description: 'Level up your styling skills. This session covers modern CSS features like Grid, Flexbox, and custom properties for creating complex layouts.',
    category: 'Workshop',
  },
    {
    id: '7',
    title: 'Cybersecurity Essentials',
    date: '2024-10-18',
    time: '13:00',
    location: 'Computer Science Dept, Room 101',
    description: 'Learn the fundamentals of cybersecurity, including threat detection, secure coding practices, and data protection strategies.',
    category: 'Seminar',
  },
  {
    id: '8',
    title: 'Game Dev Social',
    date: '2024-10-22',
    time: '18:00',
    location: 'Student Union Games Room',
    description: 'A casual meetup for student game developers. Share your projects, playtest new games, and find collaborators.',
    category: 'Networking',
  },
  {
    id: '9',
    title: 'Intro to Quantum Computing',
    date: '2024-10-25',
    time: '15:00',
    location: 'Physics Building, Auditorium 1',
    description: 'Demystifying the principles of quantum computing and its potential impact on technology. No prior physics knowledge required.',
    category: 'Tech Talk',
  },
  {
    id: '10',
    title: 'Building with Firebase',
    date: '2024-11-02',
    time: '10:00',
    location: 'Tech Hub, Room 101',
    description: 'A comprehensive workshop on using Firebase for authentication, databases, and hosting to build full-stack web applications quickly.',
    category: 'Workshop',
  },
  {
    id: '11',
    title: 'Data Science Career Fair',
    date: '2024-11-08',
    time: '13:00',
    location: 'Grand Ballroom, Student Union',
    description: 'Connect with top companies hiring for data scientists, analysts, and machine learning engineers. Bring your resume!',
    category: 'Networking',
  },
  {
    id: '12',
    title: 'Mobile App Dev Challenge',
    date: '2024-11-16',
    time: '09:00',
    location: 'Computer Science Dept, Main Lab',
    description: 'A weekend-long challenge to design and build a functional mobile application that solves a real-world problem. All platforms welcome.',
    category: 'Hackathon',
  },
  {
    id: '13',
    title: 'The Ethics of AI',
    date: '2024-11-20',
    time: '17:00',
    location: 'Philosophy Hall, Room 300',
    description: 'A panel discussion on the ethical implications of artificial intelligence, from algorithmic bias to autonomous systems.',
    category: 'Seminar',
  },
  {
    id: '14',
    title: 'Cloud Native & Kubernetes',
    date: '2024-11-28',
    time: '12:00',
    location: 'Online',
    description: 'Learn how to deploy, manage, and scale applications using containerization and the Kubernetes orchestration platform.',
    category: 'Workshop',
  },
  {
    id: '15',
    title: 'AR/VR Demo Day',
    date: '2024-12-04',
    time: '16:00',
    location: 'Innovation Hub',
    description: 'Experience the latest in augmented and virtual reality. Demos from student projects and local AR/VR startups.',
    category: 'Tech Talk',
  },
  {
    id: '16',
    title: 'UI/UX Design Sprint',
    date: '2024-12-10',
    time: '09:30',
    location: 'Design Lab, Art Building',
    description: 'A fast-paced, 5-day design sprint to solve a complex problem through prototyping and user testing. Limited spots available.',
    category: 'Workshop',
  },
  {
    id: '17',
    title: 'Fintech Disruption',
    date: '2024-12-15',
    time: '14:00',
    location: 'Business School, Room B12',
    description: 'Explore how technology is transforming the financial services industry, from digital payments to blockchain-based finance.',
    category: 'Seminar',
  },
  {
    id: '18',
    title: 'Intro to Go (Golang)',
    date: '2025-01-15',
    time: '18:00',
    location: 'CS Building, Room 404',
    description: 'Learn the basics of Go, a statically typed, compiled language designed at Google. Perfect for building simple, reliable, and efficient software.',
    category: 'Workshop',
  },
  {
    id: '19',
    title: 'Python for Data Analysis',
    date: '2025-01-22',
    time: '14:00',
    location: 'Library, Study Room 5',
    description: 'An introductory workshop on using Python libraries like Pandas and NumPy for data manipulation and analysis.',
    category: 'Workshop',
  },
  {
    id: '20',
    title: 'Campus Green Tech Challenge',
    date: '2025-02-01',
    time: '10:00',
    location: 'Sustainability Institute',
    description: 'A weekend-long hackathon to build technology that promotes environmental sustainability on campus.',
    category: 'Hackathon',
  },
  {
    id: '21',
    title: 'Alumni Tech Mentorship Mixer',
    date: '2025-02-08',
    time: '19:00',
    location: 'Alumni Center',
    description: 'Connect with alumni working in the tech industry. Get career advice, find mentors, and expand your professional network.',
    category: 'Networking',
  },
  {
    id: '22',
    title: 'Building Scalable APIs with GraphQL',
    date: '2025-02-12',
    time: '17:00',
    location: 'Online',
    description: 'A tech talk on the advantages of GraphQL over traditional REST APIs and a live demo of building a GraphQL server.',
    category: 'Tech Talk',
  },
  {
    id: '23',
    title: 'Intro to UX Research',
    date: '2025-02-19',
    time: '13:00',
    location: 'Design Lab, Art Building',
    description: 'Learn about user experience research methods, including user interviews, surveys, and usability testing.',
    category: 'Seminar',
  },
  {
    id: '24',
    title: 'Robotics Club Showcase',
    date: '2025-03-01',
    time: '15:00',
    location: 'Engineering Building, Atrium',
    description: 'See the latest creations from the campus robotics club, from autonomous drones to helper bots.',
    category: 'Tech Talk',
  },
  {
    id: '25',
    title: 'Career Talk: Life at a FAANG Company',
    date: '2025-03-05',
    time: '16:00',
    location: 'Lecture Hall A',
    description: 'Hear from a panel of software engineers about their experiences working at top tech companies like Google, Apple, and Amazon.',
    category: 'Seminar',
  },
  {
    id: '26',
    title: 'End of Semester Project Fair',
    date: '2025-03-12',
    time: '11:00',
    location: 'Student Union, Grand Ballroom',
    description: 'Students from various tech-related courses will showcase their final projects. A great opportunity to see what your peers are building!',
    category: 'Networking',
  }
];
